name: Build & publish image 3
on: workflow_dispatch
jobs:
  gen-build-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      IMAGE_NAME: test-package-3
      REPLACE_STRING: replaced-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Replace strings
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "replace_me"
          replace: ${{ env.REPLACE_STRING }}
          regex: false
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: miampf
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./test-package-3/Dockerfile
          push: true
          tags: ghcr.io/miampf/${{ env.IMAGE_NAME }}:v0.${{ github.run_attempt }}.0,ghcr.io/miampf/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
