name: Build & publish images
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  replace-strings:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./test-package-1/Dockerfile
            image: ghcr.io/miampf/test-package-1
          - dockerfile: ./test-package-2/Dockerfile
            image: ghcr.io/miampf/test-package-2
          - dockerfile: ./test-package-3/Dockerfile
            image: ghcr.io/miampf/test-package-3
    env:
      REPLACE_STRING: replaced-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
   permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Replace strings
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "replace_me"
          replace: ${{ env.REPLACE_STRING }}
          regex: false
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: miampf
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
